services:
  backend:
    build: ./backend
    container_name: transcendence_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=/database/data/database.db #self reminder rcruz
    volumes:
      - ./backend/src:/app/src
      - backend_data:/app/data
      - sqlite_database:/database/data #self reminder rcruz
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
      - VITE_WS_URL=ws://backend:3000
    volumes:
      - ./frontend/conf:/app/front-end/conf
      - ./frontend/src:/app/front-end/src
    networks:
      - transcendence
    restart: unless-stopped

  waf:
    build: ./waf
    container_name: transcendence_waf
    ports:
      - "8080:80"
    volumes:
      - ./waf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./waf/modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./waf/crs-setup.conf:/etc/modsecurity/crs-setup.conf:ro
    networks:
      - transcendence
    restart: unless-stopped

  vault:
    image: vault:1.13.3
    container_name: transcendence_vault
    restart: on-failure:10
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8200","tls_disable":"0", "tls_cert_file":"/data/vault-volume/certificate.pem", "tls_key_file":"/data/vault-volume/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-volume:/data
    healthcheck:
      retries: 5
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"
    networks:
      - transcendence

volumes:
  sqlite_database:
  backend_data:
  vault-volume:

networks:
  transcendence:
    name: transcendence
    driver: bridge

