version: '3.8'

services:

  database:
    build: ./database
    image: mariadb:v1.0
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_database:/var/lib/mysql
    networks:
      - transcendence
    init: true
    restart: always

  backend:
    build: ./backend
    container_name: transcendence_backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./backend/src:/app/src
      - backend_data:/app/data
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_WS_URL=ws://backend:3001
    volumes:
      - ./frontend/conf:/app/front-end/conf
      - ./frontend/src:/app/front-end/src
    networks:
      - transcendence
    restart: unless-stopped

    waf:
    build: ./waf
    container_name: transcendence_waf
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./waf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./waf/modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./waf/crs-setup.conf:/etc/modsecurity/crs-setup.conf:ro
      - ./waf/modsecurity_rules.conf:/etc/modsecurity/modsecurity_rules.conf:ro
    networks:
      - transcendence
    restart: unless-stopped

    vault:
      image: vault:latest
      container_name: transcendence_vault
      restart: on-failure:10
      ports:
        - "8200:8200"
      environment:
        VAULT_ADDR: 'https://0.0.0.0:8200'
        VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8200","tls_disable":"0", "tls_cert_file":"/data/vault-volume/certificate.pem", "tls_key_file":"/data/vault-volume/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
        VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
        VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
      cap_add:
        - IPC_LOCK
      volumes:
        - vault-volume:/data
      healthcheck:
        retries: 5
      command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"
      networks:
        - transcendence

volumes:
  mariadb_database:
  backend_data:
  vault-volume:

networks:
  transcendence:
    name: transcendence
    driver: bridge

