services:
  backend:
    build: ./backend
    container_name: transcendence_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=/database/data/database.db #self reminder rcruz
    volumes:
      - ./backend/src:/app/src
      - backend_data:/app/data
      - frontend_dist:/app/frontend
      - sqlite_database:/database/data #self reminder rcruz
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
      - VITE_WS_URL=ws://backend:3000
    volumes:
      - ./frontend/conf:/app/front-end/conf
      - ./frontend/src:/app/front-end/src
      - frontend_dist:/app/front-end/dist
    networks:
      - transcendence
    restart: unless-stopped

  waf:
    build: ./waf
    container_name: transcendence_waf
    ports:
      - "8080:80"
    networks:
      - transcendence
    restart: unless-stopped

  vault:
        build:
            context: "./vault/"
            args:
                VAULT_API_PORT: "${VAULT_API_PORT:-8200}"
        container_name: vault
        restart: no
        ports:
            - "${VAULT_ROOT_TOKEN_EXCHANGE_PORT:-4141}:${VAULT_ROOT_TOKEN_EXCHANGE_PORT:-4141}"
        networks:
          - transcendence
                ipv4_address: &vault_ip 10.42.42.42
        extra_hosts:
            backend: *backend-ip
            frontend: *frontend-ip
        cap_add:
            - IPC_LOCK
        volumes:
            - "vault-storage:/vault/file/"
            - "vault-secret:/vault/secret/"
            - "vault-logs:/vault/logs/"


volumes:
  sqlite_database:
  backend_data:
  vault-volume:
  frontend_dist:

networks:
  transcendence:
    name: transcendence
    driver: bridge

