services:
  backend:
    build: 
      context: ./backend
      args:
        NODE_ENV: development  # Pass NODE_ENV as build arg
    container_name: transcendence_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=/database/data/database.db
    volumes:
      - ./backend/src:/app/src                    # Hot reload for source
      - ./backend/package.json:/app/package.json  # Track dependency changes
      - /app/node_modules                         # Prevent local node_modules override
      - backend_data:/app/data
      - frontend_dist:/app/frontend
      - sqlite_database:/database/data
    networks:
      - transcendence
    restart: unless-stopped
    # Add this for better development experience
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://backend:3000
      - VITE_WS_URL=wss://backend:3000
    volumes:
      - ./frontend/conf:/app/front-end/conf
      - ./frontend/src:/app/front-end/src
      - /app/front-end/node_modules                           # Prevent local node_modules override
      - frontend_dist:/app/front-end/dist
    networks:
      - transcendence
    restart: unless-stopped
    # Add this for better development experience
    stdin_open: true
    tty: true

volumes:
  sqlite_database:
  backend_data:
  frontend_dist:

networks:
  transcendence:
    name: transcendence
    driver: bridge